### PR TITLE
fix downlink parser

### LINKED ISSUE #343: Downlink Event Parser does not temporarily save old values
Consider the following sequence of items in telemetry:
- A state field called `x`, which has a value of 5
- An event called `y` which has `x` as a data field, which occurred at time `t`, at which point `x had a value of 2

Rather than the final reported telemetry from the downlink parser for `x` having a value of 5, it will have a value of `2` because calling deserialize() for the event causes the value of `x` to be overwritten.

To solve this problem, the data fields of `y` should be saved prior to deserializing `y`, and then their values should be re-applied.

### PR DESCRIPTION
**Pull request by fatimayousuf**
# Fix Downlink Parser Bug

Fixes #343 

### Summary of changes
Record the original values of the event data fields before deserializing the event, and then reapplying the original values to the fields after the downlink is parsed

### Testing
In the test file, I changed the event data field (data1_f) from false to true after the event was signaled. I then tested that data1_f remained true even after the downlink was parsed.

### CODE REVIEW

File: src/gsw/parsers/src/DownlinkParser.cpp [hunk 1]
```diff
@@ -146,21 +146,35 @@ std::string DownlinkParser::process_downlink_packet(const std::vector<char>& pac
             for(ReadableStateFieldBase* field : flow->field_list) {
                 Event* event = registry.find_event(field->name());
                 if (event) {
+                    // Store the original values of the control cycle count and data fields
+                    unsigned int current_ccno = event->ccno->get();
```
Comment (tanishqaggarwal) [inline src/gsw/parsers/src/DownlinkParser.cpp]: I don't think we need to restore the ccno stored inside the event, since it never gets overridden by anything.

Comment (fatimayousuf) [reply src/gsw/parsers/src/DownlinkParser.cpp]: The event ccno is a pointer to the control cycle count in the TimedControlTask class. Even though deserialize is only called from the ground, couldn't setting the control cycle count to value stored in the downlink (the last time the event was signaled) affect things? Maybe with ptest as we try sending uplinks and downlinks without a radio in the loop?

Comment (fatimayousuf) [reply src/gsw/parsers/src/DownlinkParser.cpp]: Also if I don't restore the control cycle count, then `TEST_ASSERT_EQUAL(tf.cycle_count_fp->get(), cycle_no);` in the test file won't pass

Comment (tanishqaggarwal) [reply src/gsw/parsers/src/DownlinkParser.cpp]: Ah, you're right, they're the same pointer. I see your point.
